name: My GitHub Action WorkFlow
on: push
jobs:
    myjob:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Welcome Message
          run: echo "Hello World"
        