name: My GitHub Action WorkFlow
on: push
jobs:
    myjob:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Welcome Message
          run: echo "Hello World"
        - name: Display Dog
          run: |
              sudo apt-get install cowsay -y
              cowsay -f dog >> dog.txt
              cat dog.txt
